name: test-workflow
on: push
jobs:
  build:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: hello-step
        run: echo "running demo build"
  test:
    name: testing demo
    runs-on: ubuntu-latest
    step:
      - name: test step
        run: echo "this is test step"


